### ISSUE TITLE
Admin print history table: filtering by modifier not works

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#454]
The tabulator's ajax throws 500 error

**Comment by luksan47** [comment]
Getting these in the server, I think caused by this. Hopefully fixed with #503 

```
[2020-10-23 17:23:30] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'modifier' in 'where clause' (SQL: select count(*) as aggregate from `print_account_history` inner join `users` as `user` on `user`.`id` = `user_id` inner join `users` as `modifier` on `modifier`.`id` = `modified_by` where `modifier` like %Molnár%) {"userId":169,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'modifier' in 'where clause' (SQL: select count(*) as aggregate from `print_account_history` inner join `users` as `user` on `user`.`id` = `user_id` inner join `users` as `modifier` on `modifier`.`id` = `modified_by` where `modifier` like %Molnár%) at /var/www/uran/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
[stacktrace]
...
#8 /var/www/uran/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(730): Illuminate\\Database\\Query\\Builder->getCountForPagination()
#9 /var/www/uran/app/Utils/TabulatorPaginator.php(61): Illuminate\\Database\\Eloquent\\Builder->paginate('20')
#10 /var/www/uran/app/Http/Controllers/Dormitory/PrintController.php(213): App\\Utils\\TabulatorPaginator->paginate()
#11 [internal function]: App\\Http\\Controllers\\Dormitory\\PrintController->listPrintAccountHistory()
#12 /var/www/uran/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#13 /var/www/uran/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('listPrintAccoun...', Array)
#14 /var/www/uran/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Dormitory\\PrintController), 'listPrintAccoun...')
...

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'modifier' in 'where clause' at /var/www/uran/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)
...
#12 /var/www/uran/app/Utils/TabulatorPaginator.php(61): Illuminate\\Database\\Eloquent\\Builder->paginate('20')
#13 /var/www/uran/app/Http/Controllers/Dormitory/PrintController.php(213): App\\Utils\\TabulatorPaginator->paginate()
#14 [internal function]: App\\Http\\Controllers\\Dormitory\\PrintController->listPrintAccountHistory()
...
```
